services:
  - type: web
    name: pma-warrior
    env: node
    buildCommand: chmod +x render-build.sh && ./render-build.sh
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: pma-database
          property: connectionString
databases:
  - name: pma-database
    databaseName: pma_warrior
    user: pma_user